### ISSUE TITLE
content weight question

### ISSUE THREAD

**Issue by lulu1315** [nkolkin13/STROTSS#1]
hello and thanks a lot for the code.
I have a little confusion about content weight.
you multiply the user input by 16 and divide by 2 at the end of each iteration
so for max_scl = 5 and a user input of content weight = 1
scl = 1 : content weight = 16
scl = 2 : content weight = 8
scl = 3 : content weight = 4
scl = 4 : content weight = 2

shouldn't it be multiplied by 32 (or 2^max_scale)
not a big deal but just wanted to be sure.
thanks
luc

**Comment by nkolkin13** [comment]
Hi Luc,
Thank you for pointing this out! I made a mistake and It looks like I've been using double the content weight I thought I was throughout the project, I'll update section 2.5 of the paper to say that the default alpha is 2.0. With this in mind it should probably be multiplied by 2^(max_scale-1) (since scl loops over range(1,max_scl), not range(max_scl)). Thanks again for pointing this out!
Best,
Nick

**Comment by lulu1315** [comment]
ok.thanks
